import { isDev } from "./utils/environment";
import { config } from "dotenv"
import path from 'path';

// __dirname (not appPath) always matches where webpack's CopyPlugin actually places .env:
// alongside index.js. appPath is the asar root in production, which is one level higher
// than that - dotenv would silently fail to find any .env there and OPENAI_API_KEY would
// never get set. This only "worked" in dev by accident, since dev's appPath happens to be
// the project root, which also has the original (uncopied) .env at its top level.
config({ path: path.join(__dirname, ".env") })

import { app, BrowserWindow } from 'electron';
import setupToolbar from './app/window/toolbar';
import { configureDatabase } from "./vcs/database/setup";
import { prismaClient } from './vcs/database/client';
import TimestampProvider from './vcs/database/utils/timestamp-provider';
import LocalDatabaseVCSServer from './vcs/infrastructure/servers/local-database-server';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// eslint-disable-next-line @typescript-eslint/no-require-imports -- electron-squirrel-startup ships no types/ESM export
if (require('electron-squirrel-startup')) {
    app.quit();
}

const createWindow = async (): Promise<void> => {
    // Create the browser window.
    const mainWindow = new BrowserWindow({
        height: 1080,
        width: 1920,
        title: "Ghost Editor",
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
    });

    setupToolbar(mainWindow)

    await configureDatabase()
    await TimestampProvider.setup()
    new LocalDatabaseVCSServer(mainWindow)

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    // Open the DevTools.
    if (isDev) { mainWindow.webContents.openDevTools(); }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', async () => {
    if (process.platform !== 'darwin') {
        app.quit();

        await TimestampProvider.flush()
        await prismaClient.$disconnect()
    }
});

app.on('activate', () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});
